version: 0.0
os: linux

files:
  - source: https://raw.githubusercontent.com/goodkyu/awstest/main/test.jsp
    destination: /var/lib/tomcat/webapps/test.jsp

file_exists_behavior: OVERWRITE

hooks:
  AfterInstall:
    - location: server_start.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: server_stop.sh
      timeout: 300
      runas: root
